// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqT-g75J0WtV08YmK4SR6FAHPQQOZ5Jh4',
    appId: '1:98680161120:web:a86ab19937628ad2949405',
    messagingSenderId: '98680161120',
    projectId: 'camera-app-b837f',
    authDomain: 'camera-app-b837f.firebaseapp.com',
    storageBucket: 'camera-app-b837f.firebasestorage.app',
    measurementId: 'G-QB608FV972',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkiaYTWkQUTT99iAi7FX-WXJs_z4ByJPw',
    appId: '1:98680161120:android:c14ab7a32176cd58949405',
    messagingSenderId: '98680161120',
    projectId: 'camera-app-b837f',
    storageBucket: 'camera-app-b837f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv0aJnnbEAzEaUjXHfaW2sb9fuqOv7e9o',
    appId: '1:98680161120:ios:3fd16d0075e622d4949405',
    messagingSenderId: '98680161120',
    projectId: 'camera-app-b837f',
    storageBucket: 'camera-app-b837f.firebasestorage.app',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv0aJnnbEAzEaUjXHfaW2sb9fuqOv7e9o',
    appId: '1:98680161120:ios:3fd16d0075e622d4949405',
    messagingSenderId: '98680161120',
    projectId: 'camera-app-b837f',
    storageBucket: 'camera-app-b837f.firebasestorage.app',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqT-g75J0WtV08YmK4SR6FAHPQQOZ5Jh4',
    appId: '1:98680161120:web:03b04bc3ae0985c1949405',
    messagingSenderId: '98680161120',
    projectId: 'camera-app-b837f',
    authDomain: 'camera-app-b837f.firebaseapp.com',
    storageBucket: 'camera-app-b837f.firebasestorage.app',
    measurementId: 'G-KYDBQWSECC',
  );
}
